version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /workspaces/upptime
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /workspaces/confluence
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /workspaces/github-marketplace
    schedule:
      interval: weekly
